# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: kubeissuer
# spec:
#   acme:
#     # The ACME server URL
#     server: https://acme-v02.api.letsencrypt.org/directory
#     # Email address used for ACME registration
#     email: iamjignyasa@gmail.com
#     # Name of a secret used to store the ACME account private key
#     privateKeySecretRef:
#       name: kubeissuer
#     # Enable the HTTP-01 challenge provider
#     solvers:
#     - http01:
#         ingress:
#           class: nginx         
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: iamjignyasa@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - http01:
          ingress:
            class: nginx
