apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-one-two
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - metallb.com
      secretName: letsencrypt-production
  rules:
  - host: metallb.com
    http:
      paths:
      - path: /one
        pathType: Prefix
        backend:
          service:
            name: app-one
            port:
              number: 8080
      - path: /two
        pathType: Prefix
        backend:
          service:
            name: app-two
            port:
              number: 8080
  
