apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
 name: canary-gateway
spec:
 selector:
   istio: ingressgateway # using Istio IngressGateway
 servers:
 - port:
     number: 80
     name: http
     protocol: HTTP
   hosts:
   - "*"