apiVersion: apps/v1
kind: Deployment
metadata:
  name: api2
  namespace: myapp-namespace
  labels:
    app: api2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api2
  template:
    metadata:
      labels:
        app: api2
    spec:
      containers:
      - name: api2
        image: jignyasamishra/api2:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: api2
spec:
  selector:
    app: api2
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
