apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: one
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: "mongodb"
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
        readinessProbe:
          exec:
            command:
            - mongosh
            - --eval
            - "db.stats()"
          initialDelaySeconds: 10
          periodSeconds: 5
      initContainers:
      - name: init-mongo-client
        image: mongo:latest
        command: ['sh', '-c', 'until mongosh --eval "db.stats()" > /dev/null 2>&1; do echo waiting for mongo; sleep 2; done;']
  volumeClaimTemplates:
  - metadata:
      name: mongo-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: one  # Ensure the correct namespace is specified
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP