apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc
spec:
  accessModes:
    - ReadWriteMany  # Ensure this matches the PV access mode
  resources:
    requests:
      storage: 10Gi  # Must be less than or equal to the PV capacity