apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: one
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: "mongodb"
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password
        volumeMounts:
        - name: data
          mountPath: /data/db
      initContainers:
      - name: init-mongo-client
        image: mongo:latest
        command: ['sh', '-c', 'until mongo --host mongodb --eval "db.stats()" > /dev/null 2>&1; do echo waiting for mongo; sleep 2; done;']
        volumeMounts:
        - name: data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: standard
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: one  # Ensure the correct namespace is specified
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP