replicaCount: 1

image:
  repository: us-docker.pkg.dev/google-samples/containers/gke/hello-app
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  port: 8080
  targetPort: 8080
  type: ClusterIP

api1:
  name: app-one
  namespace: default

api2:
  name: app-two
  namespace: default

serviceAccount:
  create: false
  name: ""

ingress:
  enabled: false
  # If enabled, provide the following configuration
  # name: ""
  # nginx:
  #   path: /
  #   hosts:
  #     - host: chart-example.local
  #       paths:
  #         - /
  # tls: []
